backend:
  name: git-gateway
  branch: main

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"
publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

# media_library:
  # name: uploadcare
  # config:
    # publicKey: a73a170cb5cdef662983
    # multiple: false
    # tabs: 'file camera url facebook gdrive'
    # effects: 'crop,rotate,enhance,grayscale'
    # imageShrink: '2000x2000'
    # previewStep: true
    # clearable: true


collections:
  - name: 'about'
    label: 'About'
    folder: 'content/about'
    delete: false
    create: false
    path: 'index'
    fields:
      - { label: 'Titel', name: 'title', widget: 'string' }
      - { label: 'Auteur', name: 'author', widget: 'string' }
      - { label: 'Omschrijving', name: 'description', widget: 'string' }
      - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
      - { name: 'layout', widget: 'hidden', default: 'about' }
      - { label: 'Inhoud', name: 'body', widget: 'markdown' }
  - name: 'contact'
    label: 'Contact'
    folder: 'content/contact'
    delete: false
    create: false
    path: 'index'
    fields:
      - { label: 'Titel', name: 'title', widget: 'string', default: 'Contact' }
      - { label: 'Hoeveel uur tot antwoord', name: 'contactanswertime', widget: 'string' }
      - { name: 'layout', widget: 'hidden', default: 'about' }
      - { name: 'netlify', widget: 'hidden', default: 'true' }
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    path: '{{slug}}/index'
    media_folder: 'static/img/{{year}}/{{month}}'
    public_folder: ''
    fields:
        - { label: 'Status', name: 'status', widget: 'select', options: ['Published', 'Featured', 'Draft'], default: 'Published' }
        - { label: 'Verborgen', name: 'hidden', widget: 'boolean', required: false }
        - { label: 'Titel', name: 'title', widget: 'string' }
        - { label: 'Slug', name: 'slug', widget: 'string', default: '{{slug}}' }
        - { label: 'Keywords', name: 'keywords', widget: 'list' }
        - { label: 'Omschrijving', name: 'description', widget: 'string' }
        - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
        - { label: 'Laatst aangepast', name 'lastmod', widget: 'datetime' }
        - { label: 'Auteur', name: 'author', widget: 'string' }
        - { label: 'Tags', name: 'tags', widget: 'list' }
        - { label: 'Image'  , name: 'images', widget: image, required: false }
         - label: 'Categoriën'
          name: 'categories'
          widget: 'list'
          required: false
          fields:
            - label: 'Category'
              name: 'category'
              widget: 'relation'
              collection: 'postCategories'
              searchFields: ['title']
              valueField: 'title'
        - { label: 'Inhoud', name: 'body', widget: 'markdown' }
        - label: 'Opties'
          name: 'options'
          widget: 'object'
          fields:
          - { label: 'Commentaar', name: 'comments', widget: 'boolean', default: true }