backend:
    name: 'git-gateway'
    branch: 'main'
    squash_merges: true

media_folder: 'static/img' # Folder where user uploaded files should go
public_folder: 'img'
publish_mode: 'editorial_workflow'

slug:
    encoding: "ascii"
    clean_accents: true
    sanitize_replacement: "_"

collections:
    - name: 'algemeen'
      label: 'Algemene paginas'
      delete: false
      create: false
      files:
        - name: 'about'
          label: 'Over..'
          file: 'content/about/index.md'
          fields:
            - { label: 'Titel', name: 'title', widget: 'string' }
            - { label: 'Auteur', name: 'author', widget: 'string' }
            - { label: 'Omschrijving', name: 'description', widget: 'string' }
            - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
            - { name: 'layout', widget: 'hidden', default: 'about' }
            - { label: 'Inhoud', name: 'body', widget: 'markdown' }
        - name: 'privacy'
          label: 'Privacy beleid'
          file: 'content/privacybeleid/index.md'
          fields:
            - { label: 'Titel', name: 'title', widget: 'string' }
            - { label: 'Auteur', name: 'author', widget: 'string' }
            - { label: 'Omschrijving', name: 'description', widget: 'string' }
            - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
            - { name: 'layout', widget: 'hidden', default: 'about' }
            - { label: 'Inhoud', name: 'body', widget: 'markdown' }
        - name: 'contact'
          label: 'Contact'
          file: 'content/contact/index.md'
          fields:
            - { label: 'Titel', name: 'title', widget: 'string', default: 'Contact' }
            - { label: 'Hoeveel uur tot antwoord', name: 'contactanswertime', widget: 'string' }
            - { name: 'layout', widget: 'hidden', default: 'about' }
            - { name: 'netlify', widget: 'hidden', default: true }
    - name: 'blog'
      label: 'Blog'
      folder: 'content/blog'
      create: true
      delete: true
      path: '{{slug}}/index'
      preview_path: blog/{{slug}}'
      media_folder: ''
      public_folder: ''
      fields:
        - { label: 'Verborgen', name: 'hidden', widget: 'boolean', required: false }
        - { label: 'Titel', name: 'title', widget: 'string' }
        - { label: 'Auteur', name: 'author', widget: 'string', default: 'Zelfstandig Gezond' }
        - { label: 'Omschrijving', name: 'description', widget: 'string' }
        - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
        - { label: 'Laatst aangepast', name: 'lastmod', widget: 'datetime' }
        - name: 'images'
          label: 'Plaatjes'
          widget: 'list'
          required: false
          summary: '{{fields.alt}}'
          fields:
            - name: 'src'
              label: 'Plaatje'
              widget: 'image'
              required: true
            - name: 'alt'
              label: 'Alternatieve tekst'
              widget: 'string'
              hint: 'Zet hier de ondertitel/alternatieve tekst'
              required: true
            - name: 'attributed'
              label: 'Copyrightgegevens'
              widget: 'string'
              hint: 'Zet hier de copyrightekst neer'
              required: true
            - name: 'stretch'
              label: 'Uitrekken'
              widget: 'select'
              options: ['cover','horizontal', 'vertical']
              default: 'cover'
        - { label: 'Inhoud', name: 'body', widget: 'markdown', hint: 'Shortcodes:<ul><li>{{< abbr title= text= >}}</li></ul>' }
        - { label: 'Categoriën', name: 'categories', widget: 'list', required: true }
        - { label: 'Tags', name: 'tags', widget: 'list', required: true }
        - { label: 'Commentaar', name: 'comments', widget: 'boolean', default: true }