backend:
  name: git-gateway
  branch: main

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"
publish_mode: editorial_workflow

slug:
  encoding: "ascii"
  clean_accents: true
  sanitize_replacement: "_"

collections:
    - name: 'about'
      label: 'About'
      folder: 'content/about'
      delete: false
      create: false
      path: 'index'
      fields:
        - { label: 'Titel', name: 'title', widget: 'string' }
        - { label: 'Auteur', name: 'author', widget: 'string' }
        - { label: 'Omschrijving', name: 'description', widget: 'string' }
        - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
        - { name: 'layout', widget: 'hidden', default: 'about' }
        - { label: 'Inhoud', name: 'body', widget: 'markdown' }
    - name: 'contact'
      label: 'Contact'
      folder: 'content/contact'
      delete: false
      create: false
      path: 'index'
      fields:
        - { label: 'Titel', name: 'title', widget: 'string', default: 'Contact' }
        - { label: 'Hoeveel uur tot antwoord', name: 'contactanswertime', widget: 'string' }
        - { name: 'layout', widget: 'hidden', default: 'about' }
        - { name: 'netlify', widget: 'hidden', default: true }
        
    - name: 'blog'
      label: 'Blog'
      folder: 'content/blog'
      create: true
      delete: true
      path: '{{slug}}/index'
      media_folder: ''
      public_folder: ''
      fields:
        - { label: 'Verborgen', name: 'hidden', widget: 'boolean', required: false }
        - { label: 'Titel', name: 'title', widget: 'string' }
        - { label: 'Auteur', name: 'author', widget: 'string', default: 'Zelfstandig Gezond' }
        - { label: 'Omschrijving', name: 'description', widget: 'string' }
        - { label: 'Publicatie datum', name: 'date', widget: 'datetime' }
        - { label: 'Laatst aangepast', name: 'lastmod', widget: 'datetime' }
        - label: 'Image'
          name: 'images'
          widget: 'list'
          required: false
          summary: '{{fields.alt}}'
          fields:
            - label: 'Image'
              name: 'src'
              widget: 'image'
              required: false
            - label: 'Alternatieve tekst'
              name: 'alt'
              widget: 'string'
              hint: 'Zet hier de ondertitel/alternatieve tekst'
              required: false
            - label: 'Uitrekken'
              name: 'stretch'
              widget: 'select'
              options: ['cover','horizontal', 'vertical']
              default: 'cover'
        - { label: 'Inhoud', name: 'body', widget: 'markdown' }
        - { label: 'Categoriën', name: 'categories', widget: 'list' }
        - { label: 'Tags', name: 'tags', widget: 'list' }
        - { label: 'Commentaar', name: 'comments', widget: 'boolean', default: true }